# Generated by Django 2.2.5 on 2020-12-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='created',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
